apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  awsElasticBlockStore:
      volumeID: "vol-06c1ff345c0424ef6"
      fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-pv-5
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  awsElasticBlockStore:
      volumeID: "vol-071f2cc57f27957a1"
      fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: ""
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx
  labels:
    purpose: ebs-static
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: html
  volumes:
    - name: html
      persistentVolumeClaim:
        claimName: ebs-static-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  type: LoadBalancer
  selector:
  # you should provide pod labels here
    purpose: ebs-static
  ports:
  - name: http-port
    protocol: TCP
    # service port
    port: 80
    # pod port
    targetPort: 80