apiVersion: storage.k8s.io/v1
kind: persistentvolume
metadata: 
   name: ebs-static-pv 
spec: 
  capacity: 
    storage: 25Gi
  accessModes: 
    - ReadWriteOnce
  storageClassName: ""
  awsElasticBlockStore: 
      volumeID: "vol-0e42542fab35660e2"
      fsType: ext4
---
  apiVersion: storage.k8s.io/v1
  kind: persistentvolume
  metadata: 
   name: ebs-static-pv-5
  spec:  
   capacity:
   storage: 5Gi 
  accessModes: 
    - ReadWriteOnce
  storageClassName: ""
  awsElasticBlockStore: 
      volumeID: "vol-0af904e7907d14895"
      fsType: ext4
---
  apiVersion: storage.k8s.io/v1
  kind: persistentvolumeclaim
  metadata: 
   name: ebs-static-pvc
  spec: 
    accessModes: 
      - ReadWriteOnce
  resources:
   requests: 
     storage: 10Gi 
  storageClassName: ""
    #awsBlockStore : 
     # volumeId : 
      #fsType : ext4 
#---
# kind : pod
# apiversion : v1
# metadata : 
#   name : ngnix
# spec : 
#   containers : 
#    - image : ngnix
#     name : ngnix
#     ports 
#     - containerport : 80 
#   volumeMounts : 
#     - mountpath : /usr/share/ngnix/html
#     name : html

# volumes : 
#   - name : html
#   persistentVolumeClaim : 
#      claimName : static-ebs-pvc

# ---
# kind: service
# apiversion: v1
# metadata:
#   name: ngnix-service
#   namespace: default
#   labels: 
#      name: ngnix-service
#      environment: dev
#    spec:
#      type: LoadBalancer  
#    selector:
#     course: kubernetes
#    ports:
#     - name: http-port
#       protocol: tcp
#       port: 80
#       targetport: 80     

